### ISSUE TITLE
Wondering about `component.json`?

### ISSUE THREAD

**Issue by avanderhoorn** [ifandelse/ConduitJS#3]
Just wondering why there is still a `component.json` in the repo? https://twitter.com/bower/status/321370778694217729

**Comment by ifandelse** [comment]
@avanderhoorn so sorry - this slipped past me! When I've had repos w/o a component.json, I typically get pinged by devs using [component](https://github.com/component/component) - even though it's not as widely used as bower and npm, so I still include one.

**Comment by avanderhoorn** [comment]
Makes sense!
